### ISSUE TITLE
Flickering Texture Planes

### ISSUE THREAD

**Issue by pilot1106** [gravity-EDDS/EDDS-freeware-releases#2]
**bug description**
textured shapes flicker on multiple models (i.e. Terminal upper window row, Tower floor, DHL building, ...)

**to reproduce**
1) use developer or drone cam or slew mode to go to the model
2) see some shapes/triangles changing brightness, 
like you would see when either normals are pointing in the wrong direction 
or multiple co-planar shapes are drawn over each other

**expected behavior**
no flickering

**My PC**
 - Windows 10 Pro Workstation build 2004 19041.508
 - Intel i9-9920X @ 4.20 GHz
 - 128 GB RAM
 - 3 x 1TB Nvme SSD (C:Win10, D:Data, F:Flightsimulator (Premium Delux Edition 1.8.3.0) + some spinning disks
 - NVIDIA 2800Ti

**additional comment**
Thanks for sharing, looks like a good start!
I'm there to help (if I can)
In case you'd like to turn this into a open source community project (i.e. CC BY-NC-SA) I will contribute and share my blender models too.

**Comment by nsteffens** [comment]
Thanks for that issue! 
Redirected that to the 3D-Artists we are working with, they were aware of that and it's also fixed in the current development version. Feel free to join our discord to get even better insights: https://discord.gg/fhSuaQ

**Comment by michaelpietzsch** [comment]
I have this issue aswell. How can keep track of this project. I happen to live in the area, can i support you guys?

**Comment by pilot1106** [comment]
Hi Michael,

I'm part of the project by now and work on the issues mentioned above. There are still plenty of buildings which need to be modeled. If you have time and experience in blender/texturing (i.e. substance painter or materialize), you are more than welcome. If you don't know the SDK, that's not an issue, as we can help you to bring the blender models in MSFS once created.
