### ISSUE TITLE
LOD visibility incorrect

### ISSUE THREAD

**Issue by pilot1106** [gravity-EDDS/EDDS-freeware-releases#3]
**bug description**
Some objects disappear to early / appear to late

**to reproduce**
1. go west of GAT, where the blast fence/concrete blocks are
2. move/slew away
3. see concrete blocks disappear when you move away while the blast feces remain visible within reasonable reange

**Expected behavior**
LOD / visibility of objects similar size (blast fence / concrete blocks) is about equal

**My PC**
see other bug report

**Comment by nsteffens** [comment]
Redirected to our sdk-experts 👍

**Comment by titanier2002** [comment]
I had a look on this part of the items, but there is nothing we can change, seems this range visibility is made by the simulator.
