### ISSUE TITLE
Maybe we should join forces

### ISSUE THREAD

**Issue by theaudience** [gravity-EDDS/EDDS-freeware-releases#4]
Hello,

I am the author of https://github.com/theaudience/EDDS-Stuttgart-Airport-Scenery and also started to work on a Scenery for MSFS 2020.
Maybe we can work together and build something great. If yes, please get in touch with me.

Best,

Jochen

**Comment by nsteffens** [comment]
Hey Jochen! Thanks for your message! Since we are communicating through discord, feel free to join our server and send me (Nico) a message :-)

https://discord.gg/fhSuaQ
