### ISSUE TITLE
EDDS since new update #6 (1.10.11.0) is now without runway und taxiways. Buildings are seen.

### ISSUE THREAD

**Issue by HubertGer** [gravity-EDDS/EDDS-freeware-releases#5]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nsteffens** [comment]
Thank you for the report. 

We are aware of this - A new version that fixes these issues will be released this evening, along with a lot of other new features 👍
