### ISSUE TITLE
blue taxiway lights on the runway/taxiway after FS2020 update 1.13.16.0

### ISSUE THREAD

**Issue by okurz** [gravity-EDDS/EDDS-freeware-releases#8]
## Observation
The Microsoft Flight Simulator 2020 https://forums.flightsimulator.com/t/release-release-notes-1-13-16-0-world-update-iii-united-kingdom-now-available/365854 brought some updates regarding taxi light placing:

> * New airport light system
> * Add a button in airport properties to generate taxiway signs

this seems to have changed the position of taxi lights on the scenery.

## Expected result
No blue taxi light stands on the runway nor directly on the taxi ways

**Comment by titanier2002** [comment]
Hi Okurz,
we have fixed this allready and it will be in our next update.

**Comment by okurz** [comment]
Just checked the new version during day and night and I am impressed. Good job! And thank you!
