### ISSUE TITLE
Seperate Release of Navdata Fix

### ISSUE THREAD

**Issue by chrisklpp** [gravity-EDDS/EDDS-freeware-releases#9]
I used this fantastic add-on multiple times in the passt and was amazed by the quality, so thank you for that!

With JustStim EDDS available in the store i couldn't resist testing it out as well, since EDDS is my home airport. Unfortunately they are missing the Navdata (SID/STAR) while you have managed to add those in manually.

Is there any way to release a separate little fix with only the Navdata to used with the JustSim EDDS (or can you link to any resources explaining how to edit this myself)

Thanks a lot for releasing this great EDDS scenery as freeware!

**Comment by titanier2002** [comment]
Hello Chrisklpp,

thanks for your kind words, but we dont want to release the navdatas without the airport, becauce we dont want to support justsim and the way they do sceneries.

best regards,
Jonas

**Comment by chrisklpp** [comment]
That’s a valid standpoint as I learned in the last days and weeks. 
Thank you nevertheless
